baseURL = 'https://Exxa1.github.io/my-site-without-theme'
languageCode = 'en-us'
title = 'My New Hugo Site'


# Added for Tailwind CSS support
[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
[caches]
  [caches.images]
    dir = ':cacheDir/images'